name: HeroesSkillTree
main: me.Whatshiywl.heroesskilltree.HeroesSkillTree
version: 1.3-Beta
authors: [Whatshiywl]
description: Brings skill trees to the Heroes plugin.
depend: [Heroes]
commands:
  skillup:
    aliases: ['sup']
    description: Levels up a skill
  skilldown:
    aliases: ['sdown']
    description: Levels down a skill
  skillinfo:
    aliases: ['sinfo']
    description: Shows a skill's information regarding the tree
  skillpoints:
    aliases: ['sp']
    description: Shows the player's remaining SkillPoints
  skilladmin:
    alias: ['sa']
    description: Admin commands
permissions:
  skilltree.*:
    description: Gives all permissions
    default: op
    children:
      skilladmin.*: true
      skilltree.override.*: true
      skilltree.up: true
      skilltree.down: true
      skilltree.lock: true
      skilltree.info: true
  skilladmin.*:
    description: Gives all admin permissions
    children:
      skilladmin.set: true
      skilladmin.give: true
      skilladmin.remove: true
      skilladmin.clear: true
      skilladmin.reset: true
  skilltree.override.*:
    description: Gives player total override powers over skill limitations
    children: 
      stilltree.override.locked: true
      skilltree.override.unlock: true
      skilltree.override.usepoints: true
  skilladmin.set:
    description: Allows player to set his/others' SkillPoints
  skilladmin.give:
    description: Allows player to increase his/others' SkillPoints
  skilladmin.remove:
    description: Allows player to decrease his/others' SkillPoints
  skilladmin.clear:
    description: Allows players to clear out his/others' SkillPoints
  skilladmin.reset:
    description: Allows players to reset his/others' skills and SkillPoints
  skilltree.override.locked:
    description: Allows player to use locked skills
  skilltree.override.unlock:
    description: Allows players to unlock skills freely ignoring parentship
  skilltree.override.usepoints:
    description: Player's points don't increase/decrease when leveling up/down skills
  skilltree.up:
    description: Allows leveling up skills
    default: true
  skilltree.down:
    description: Allows leveling down skills
  skilltree.lock:
    description: Allows player to re-lock a skill
  skilltree.info:
    description: Allows player to check a skill's info
    default: true
  skilltree.points:
    description: Allows player to check his SkillPoints
    default: true